In [24]:
import os

os.chdir(r"C:\Users\ASUS\OneDrive\Desktop\nifty100_project")

print(os.getcwd())

C:\Users\ASUS\OneDrive\Desktop\nifty100_project

In [25]:
import sqlite3

conn = sqlite3.connect("database/nifty100.db")

cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

tables = cursor.fetchall()

for table in tables:
    print(table[0])

conn.close()

analysis
balancesheet
cashflow
companies
documents
financial_ratios
market_cap
peer_groups
profitandloss
prosandcons
sectors
stock_prices

In [26]:
import pandas as pd

df = pd.read_excel(
    "data/raw/companies.xlsx",
    header=1
)

print(df.shape)

(92, 12)

In [27]:
from src.etl.cleaner import *

df = clean_text(df)
df = fill_missing(df)
df = remove_duplicates(df)

print(df.shape)
df.head()

(92, 12)

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

In [28]:
import sqlite3

conn = sqlite3.connect("database/nifty100.db")

cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

tables = cursor.fetchall()

print("Tables in Database:")

for table in tables:
    print(table[0])

conn.close()

Tables in Database:
analysis
balancesheet
cashflow
companies
documents
financial_ratios
market_cap
peer_groups
profitandloss
prosandcons
sectors
stock_prices

In [31]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(
    r"C:\Users\ASUS\OneDrive\Desktop\nifty100_project\database\nifty100.db"
)

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

tables

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6         market_cap
7        peer_groups
8      profitandloss
9        prosandcons
10           sectors
11      stock_prices

In [32]:
print(os.getcwd())

C:\Users\ASUS\OneDrive\Desktop\nifty100_project